disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ian Writes Some Code"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "02 January 2006"

["params.author"]
name = "Ian Koh"
headline = "I _hate_ CSS"
